# Site settings
title: the dabbling developer
email: voodoorapter014@gmail.com
description: "A blog about software development, well mostly.."
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
plugins:
  - jekyll-stemap
twitter_username: twitter_username
github_username:  "Vasu014"
linkedin_username: vasu-bhardwaj-2a4b6080
repository: Vasu014/Vasu014.github.io
# Build settings
markdown: kramdown
future: true
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"
collections:
  portfolio:
    output: false
    permalink: /portfolio/:path/
  posts:
    output: true
    permalink: /posts/:path  
  
